DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS author_nickname_history;
DROP TABLE IF EXISTS author_description_history;
DROP TABLE IF EXISTS author_chocolates_history;
DROP TABLE IF EXISTS author_analyzed;
DROP TABLE IF EXISTS author_diary;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS account_diary;
DROP TABLE IF EXISTS letter;
DROP TABLE IF EXISTS diary_group;
DROP TABLE IF EXISTS diary_group_author;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS feedback_diary;
DROP TABLE IF EXISTS feedback_author;
-- DROP TABLE IF EXISTS about;
DROP TABLE IF EXISTS app;
