-- kor
INSERT INTO wise_saying (language, saying, nickname) VALUES
  ('kor', '세상에서 가장 아름답고 소중한 것은 보이거나 만져지지 않는다. 단지 가슴으로만 느낄 수 있다.', '헬렌 켈러'),
  ('kor', '친구여, 인생은 아주 짧다. 싸우거나 말다툼할 시간이 없다.', '비틀즈'),
  ('kor', '우리가 사는 것도 꿈꿀 때나 마찬가지다, 혼자이기는.', '조세프 콘라드'),
  ('kor', '지성은 일어난 일을 알고 천재는 일어날 일을 안다.', '제임스 조이스'),
  ('kor', '천재는 실수하지 않는다. 발견을 위해 의도적으로 할 뿐이다.', '존 치아디'),
  ('kor', '3시는 하고 싶은 일을 시작하기에는 언제나 너무 이른 때이다.', '장 폴 사르트르'),
  ('kor', '가장 하기 힘든 일은 아무 일도 안하는 것이다.', '유대인 격언'),
  ('kor', '예술이 만드는 추한 것들은 종종 시간이 흐르면서 아름다워진다.', '장 꼭또'),
  ('kor', '세상은 고통으로 가득하지만 한편 그것을 이겨내는 일로도 가득차 있다.', '헬렌 켈러'),
  ('kor', '시간은 위대한 스승이기는 하지만 불행히도 자신의 모든 제자를 죽인다.', '헥토르 베를리오즈'),
  ('kor', '힘 있을 때 친구는 친구가 아니다.', '헨리 애덤스'),
  ('kor', '평화로울 때 땀을 더 흘리면 전쟁에서 피를 덜 흘린다.', '하이먼 리코버'),
  ('kor', '사람은 아무도 다른 사람을 정말로 이해할 수 없고 아무도 다른 사람의 행복을 만들어 줄 수 없다.', '그레이엄 그린'),
  ('kor', '과거를 지배하는 자가 미래를 지배하며 현재를 지배하는 자가 과거를 지배한다.', '조지 오웰'),
  ('kor', '처음에는 네가 술을 마시고, 다음에는 술이 술을 마시고, 다음에는 술이 너를 마신다.', 'F. 소코트 피츠제랄드'),
  ('kor', '언제부터 천재가 존경받았는가?', '엘리자베스 바렛 브라우닝'),
  ('kor', '바람과 파도는 항상 가장 유능한 항해자의 편에 선다.', '에드워드 기본'),
  ('kor', '스스로를 신뢰하는 사람만이 다른 사람들에게 성실할 수 있다.', '에릭 프롬'),
  ('kor', '1년간의 행복을 위해서는 정원을 가꾸고, 평생의 행복을 원한다면 나무를 심어라.', '영국 속담'),
  ('kor', '승리하면 조금 배울 수 있고 패배하면 모든 것을 배울 수 있다.', '크리스티 매튜슨'),
  ('kor', '사람이 먼 일을 생각하지 않으면 바로 앞에 슬픔이 닥치는 법이다.', '공자'),
  ('kor', '행복이란 포근한 강아지 한 마리다.', '찰스 M. 슐츠'),
  ('kor', '당신이 잘 하는 일이라면 무엇이나 행복에 도움이 된다.', '버트랜드 러셀'),
  ('kor', '첫사랑이 신비로운 것은 우리가 그것이 끝날 수 있다는 것을 모르기 때문이다.', '벤자민 디즈렐리'),
  ('kor', '사람은 살려고 태어나는 것이지 인생을 준비하려고 태어나는 것은 아니다. 인생 그 자체, 인생의 현상, 인생이 가져다 주는 선물은 숨이 막히도록 진지하다!', '보리스 파스테르나크'),
  ('kor', '훌륭한 여행가들이 흔히 그렇듯이 나는 내가 기억하는 것보다 많은 것을 보았고 또한 본 것보다 많은 것을 기억한다.', '벤자민 디즈렐리'),
  ('kor', '안다는 것은 전혀 중요하지 않다. 상상하는 것이 가장 중요하다.', '아나톨 프랑스'),
  ('kor', '원수를 만들어보지 않은 사람은 친구도 사귀지 않는다.', '알프레드 테니슨 경'),
  ('kor', '상식은 18세 때까지 후천적으로 얻은 편견의 집합이다.', '앨버트 아인슈타인'),
  ('kor', '나는 미래에 대해서는 결코 생각하지 않는다. 미래는 곧 오고 말것이므로.', '앨버트 아인슈타인'),
  ('kor', '학문에 왕도는 없다.', '유클리드'),
  ('kor', '스스로를 신뢰하는 사람만이 타인에게 성실할 수 있는 법이다.', '에리히 프롬'),
  ('kor', '주사위는 던져졌도다.', '율리우스 카이사르'),
  ('kor', '행복과 불행은 그 운이 정해진 것이 아니라 스스로 찾아지는 것이다.', '중국 속담'),
  ('kor', '돈은 사람을 결코 행복하게 만든 바 없고, 앞으로도 그러지 않을 것이다. 그 본질상 행복을 만들어내는 요소가 전혀 없기 때문이다.', '벤저민 프랭클린'),
  ('kor', '지나간 슬픔에 새 눈물을 낭비하지 말라.', '에우리피데스'),
  ('kor', '시간은 내가 그 속에서 낚시질을 하는 흐름이다.', '헨리 데이비드 소로'),
  ('kor', '행동하는 사람처럼 생각하고, 생각하는 사람처럼 행동하라.', '앙리 베르그손'),
  ('kor', '세상은 한 권의 아름다운 책이다. 그러나 그 책을 읽을 수 없는 사람에게는 별 소용이 없다.', '카를로 골도니'),
  ('kor', '세상에서 가장 아름다운 것은 물론 세상 그 자체이다.', '윌리스 스티븐스'),
  ('kor', '인생에 있어서 어려운 것은 선택이다.', '조지 무어'),
  ('kor', '자연은 인간을 결코 속이지 않는다. 우리를 속이는 것은 항상 우리 자신이다.', '장자크 루소'),
  ('kor', '인생 그 자체가 하나의 인용이다.', '호르헤 루이스 보르헤스'),
  ('kor', '친구에게 충고할 때는 즐겁게 하지 말고, 도움이 되도록 하라.', '솔론'),
  ('kor', '용서는 복수보다 낫다.', '에픽테토스'),
  ('kor', '자유가 아니면 죽음을 달라.', '패트릭 헨리'),
  ('kor', '잘못은 그것을 통하여 우리가 발전할 수 있는 훈련이다.', '윌리엄 엘러리 채닝'),
  ('kor', '뜻이 있는 곳에 길이 있다.', '속담'),
  ('kor', '땀이 없으면 달콤함도 없다.', '속담'),
  ('kor', '지나간일은 잊어 버리세요.', '속담')
  ;
  
INSERT INTO wise_saying (language, saying, nickname) VALUES
  ('eng', 'The best and most beautiful things in the world cannot be seen of even touched. They must be felt with the heart.', 'Helen Keller'),
  ('eng', 'Life is very short. And there''s no time for fussing and fighting, my friends.', 'the beatles'),
  ('eng', 'We live as we dream - alone.', 'Joseph Conrad'),
  ('eng', 'A man of genius makes no mistakes. His errors are volitional and are portals of discovery.', 'James Joyce'),
  ('eng', 'Intelligence recognizes what has happened. Genius recognizes what will happen.', 'John Ciardi'),
  ('eng', '3 O''clock is always too early for anything you want to do.', 'Jean-Paul Sartre'),
  ('eng', 'The hardest work is to go idle.', 'Jewish proverb'),
  ('eng', 'Art produces ugly things which frequently become beautiful with time.', 'Jean Cocteau'),
  ('eng', 'Although the world is full of suffering, it is full also of the overcoming of it.', 'Helen Keller'),
  ('eng', 'Time is a great teacher, but unfortunately it kills all its pupils.', 'Hector Berlioz'),
  ('eng', 'A friend in power is a friend lost.', 'Henry Adams'),
  ('eng', 'The more you sweat in peace, the less you bleed in war.', 'Hyman Rickover'),
  ('eng', 'No human being can really understand another, and no one can arrange another''s happiness.', 'Graham Greene'),
  ('eng', 'Who controls the past controls the future. Who controls the present controls the past.', 'George Orwell'),
  ('eng', 'First you take a drink, then the drink takes a drink, then the drink takes you.', 'F. Scott Fitzgerald'),
  ('eng', 'Since when was genius found respectable?', 'Elizabeth Barrett Browning'),
  ('eng', 'The winds and waves are always on the side of the ablest navigators.', 'Edward Gibbon'),
  ('eng', 'Only the person who has faith in himself is able to be faithful to others.', 'Erich Fromm'),
  ('eng', 'If you want to be happy for a year, plant a garden; if you want to be happy for life, plant a tree.', 'English Proverb'),
  ('eng', 'You can learn a little from victory; you can learn everything from defeat.', 'Christy Mathewson'),
  ('eng', 'If a man takes no thought about what is distant, he will find sorrow near at hand.', 'Confucius'),
  ('eng', 'Happiness is a warm puppy.', 'Charles M. Schulz'),
  ('eng', 'Anything you''re good at contributes to happiness.', 'Bertrand Russell'),
  ('eng', 'The magic of first love is our ignorance that it can ever end.', 'Benjamin Disraeli'),
  ('eng', 'Man is born to live, not to prepare for life. Life itself, the phenomenon of life, the gift of life, is so breathtakingly serious!', 'Boris Pasternak'),
  ('eng', 'Like all great travellers, I have seen more than I remember, and remember more than I have seen.', 'Benjamin Disraeli'),
  ('eng', 'To know is nothing at all; to imagine is everything.', 'Anatole France'),
  ('eng', 'He makes no friend who never made a foe.', 'Alfred, Lord Tennyson'),
  ('eng', 'Common sense is the collection of prejudices acquired by age 18.', 'Albert Einstein'),
  ('eng', 'I never think of the future. It comes soon enough.', 'Albert Einstein'),
  ('eng', 'There is no royal road to learning.', 'Euclid'),
  ('eng', 'Only the person who has faith in himself is able to be faithful to others.', 'Erich Fromm'),
  ('eng', 'The die is cast.', 'Julius Caesar'),
  ('eng', 'Happiness and misery are not fated but self-sought.', 'Chinese Proverb'),
  ('eng', 'Money never made a man happy yet, nor will it. There is nothing in its nature to produce happiness.', 'Benjamin Franklin'),
  ('eng', 'Waste not fresh tears over old griefs.', 'Euripides'),
  ('eng', 'Time is but the stream I go a-fishing in.', 'Henry David Thoreau'),
  ('eng', 'Think like a man of action and act like man of thought.', 'Henri Bergson'),
  ('eng', 'The world is a beautiful book, but of little use to him who cannot read it.', 'Carlo Goldoni'),
  ('eng', 'The most beautiful thing in the world is, of course, the world itself.', 'Wallace Stevens'),
  ('eng', 'The difficulty in life is the choice.', 'George A. Moore'),
  ('eng', 'Nature never deceives us; it is always we who deceive ourselves.', 'Jean-Jacques Rousseau'),
  ('eng', 'Life itself is a quotation.', 'Jorge Luis Borges'),
  ('eng', 'In giving advice, seek to help, not to please, your friend.', 'Solon'),
  ('eng', 'Forgiveness is better than revenge.', 'Epictetus'),
  ('eng', 'Give me liberty, or give me death', 'Patrick Henry'),
  ('eng', 'Error is the discipline through which we advance.', 'William Ellery Channing'),
  ('eng', 'Where there''s a will, there''s a way.', 'Proverb'),
  ('eng', 'No sweat, no sweet.', 'Proverb'),
  ('eng', 'Let bygones be bygones.', 'Proverb')
  ;