spring:
   profiles: debug
   datasource:
      username: root
      password: "!maria12"
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/diary
   jpa:
      show-sql: true

server:
   port: 80
   
jwt:
   jwtscret: NuP7j3DwRfbImWt59Xp6g3J7r4ahOOVd
   jwt-expiration-in-ms: 60000

#logging:
   #pattern:
      #console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M (%line) - %msg%n"
      #file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M (%line) - %msg%n"
   #level:
      #root: DEBUG
   